REM SCRIPT PARA INSTALAR .EXE BURLANDO O REQUISITO DE PRIVILÉGIO ADMIN

REM O SCRIPT CRIA UMA VARIÁVEL DE AMBIENTE COM UM VALOR "RUNASINVOKER" QUE PERMITE UM ARQUIVO 
REM SER EXECUTADO COM PRIVILÉGIOS LIMITADOS, MAS SUFICIENTES PARA REALIZAR UMA INSTALAÇÃO.

CMD /MIN /C "SET __COMPAT_LAYER=RUNASINVOKER && START "" %1"
