@ECHO OFF

:INICIO

COLOR 07

SET SN=""

REM COMANDOS PARA TRATAR A CODIFICAÇÃO DO CÓDIGO.
FOR /f "tokens=2 delims=:." %%x IN ('CHCP') DO SET cp=%%x
CHCP 1252>NUL

REM PREFIXO PARA VALIDAÇÃO DO SERIAL NUMBER
SET PREFIXO=WS125K22GI

:GRAVAÇÃO_SN
ECHO ----------------------------------------------------------------
ECHO.
SET /P SN= INSIRA O NÚMERO DE SÉRIE DA PEÇA : 
ECHO.
ECHO ----------------------------------------------------------------

SET SN_BCK=%SN%
SET /A CONTADOR=0

:LOOP_CONTADOR

IF "%SN_BCK%" == "" ( GOTO FIM )

IF %SN_BCK% NEQ "" (

	SET /A CONTADOR=%CONTADOR% + 1
 	SET SN_BCK=%SN_BCK:~0,-1%
 	GOTO LOOP_CONTADOR
)

:FIM

REM VARIÁVEIS PARA VALIDAR O COMPRIMENTO DO SN ESCANEADO
SET COMPRIMENTO_MAX_SN=15
SET COMPRIMENTO_SN=%CONTADOR%

REM CONDIÇÃO PARA VERIFICAR SE O CÓDIGO ESCANEADO POSSUI SOMENTE 15 DÍGITOS
IF %COMPRIMENTO_SN% NEQ %COMPRIMENTO_MAX_SN% (

	:ERROR
	ECHO.
	COLOR 04
	ECHO  ATENÇÃO, O SN DEVE CONTER EXATAMENTE 15 DÍGITOS!!!
	ECHO  O NÚMERO DE SÉRIE NÃO ESTÁ DE ACORDO COM O PADRÃO!!!
	ECHO  POR FAVOR, VERIFIQUE O CÓDIGO E TENTE ESCANEAR NOVAMENTE... 
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO.

	PAUSE

	CLS

	GOTO GRAVAÇÃO_SN

)

REM CONDIÇÃO PARA VERIFICAR SE O CÓDIGO ESCANEADO É UM CÓDIGO DE SN CORRETO
IF %SN:~0,10% NEQ %PREFIXO% (
	ECHO.
	COLOR 04
	ECHO  ATENÇÃO, PREFIXO INCORRETO!!!
	ECHO  O NÚMERO DE SÉRIE NÃO ESTÁ DE ACORDO COM O PADRÃO!!!
	ECHO  POR FAVOR, VERIFIQUE O CÓDIGO E TENTE ESCANEAR NOVAMENTE... 
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO.

	PAUSE

	CLS

	GOTO GRAVAÇÃO_SN

) ELSE (

	ECHO.
	COLOR 02
	ECHO  NÚMERO DE SÉRIE VALIDADO! GERANDO ETIQUETA......
	ECHO  POR FAVOR, AGUARDE A ETIQUETA SER IMPRESSA...
	ECHO.
	ECHO ----------------------------------------------------------------
	ECHO.
)

REM VÁRIAVEIS PARA ARMAZENAR O NOME DA MÁQUINA E DA IMPRESSORA COMPARTILHADA
SET "MÁQUINA=RB7-ENG-SW"
SET "IMPRESSORA=R - SALA SW ZD220"

SETLOCAL ENABLEDELAYEDEXPANSION

SET "ZPL=CT~~CD,~CC^~CT~^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD20^JUS^LRN^CI27^PA0,1,1,0^XZ^XA^MMT^PW563^LL484^LS0^BY2,3,101^FT59,318^BCN,,Y,N^FH\^FD>:%SN%>70000^FS^FT119,201^A0N,28,28^FH\^CI28^FDSN : %SN%^FS^CI27^FT174,110^A0N,56,56^FH\^CI28^FDWS125K2^FS^CI27^PQ1,0,1,Y^XZ"

ECHO !ZPL! > "%temp%\ZPLZDM.prn"

COPY "%temp%\ZPLZDM.prn" "\\%MÁQUINA%\%IMPRESSORA%"

ENDLOCAL

DEL "%temp%\ZPLZDM.prn" 2>NUL

ECHO.
ECHO ----------------------------------------------------------------
ECHO.

PAUSE

CLS & GOTO INICIO

EXIT